### ISSUE TITLE
Two packages both called sparta

### ISSUE THREAD

**Issue by AugustT** [mlindsk/sparta#1]
Hi Mads,

I've recently been made aware of your package by a user of our sparta package. Having two packages with the same name might well cause us both problems. While our package is not on CRAN it has been around since 2013 and has a large number of users amongst those monitor wildlife populations at large scales. I wonder if you would be willing to consider changing the name of your package?

Happy to discuss

Tom

https://github.com/BiologicalRecordsCentre/sparta

**Comment by mlindsk** [comment]
Dear Tom,

We can, unfortunately, not change the name. The name "sparta" holds a nice reference to "sparse 
tables" and changing this would require us to come up with an equally 
meaningful name. It is a shame that we didn't knew about your package 
beforehand, but we cross checked the packages on CRAN to avoid clashes 
on the package name. Also, having to scan all R packages on github for 
naming issues is a time consuming and challenging task, where many never 
reaches CRAN maturity. Finally, we are a few steps from publishing a paper about the sparta package.

With that being said, I can't imagine that these two packages will ever clash. It seems that the usecases are in two different worlds.

/Mads
